apiVersion: v1
kind: Pod
metadata:
  name: log-app
  labels:
    app: log-app
spec:
  containers:
  - name: log-app
    image: quay.io/leahnp/leah_log_app:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: log-storage
      mountPath: /var/log
  - name: sidecar-log-collector
    image: quay.io/samsung_cnct/k2-logging-fluent-bit-sidecar:latest
    env:
      - name:  FLUENT_ELASTICSEARCH_HOST
        value: "elasticsearch"
      - name:  FLUENT_ELASTICSEARCH_PORT
        value: "9200"
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: log-storage
      readOnly: true
      mountPath: /mnt/log
  volumes:
  - name: log-storage
    emptyDir: {}